version: '3.7'
x-minio-common:
  image: 'quay.io/minio/minio:RELEASE.2021-09-18T18-09-59Z'
  command: 'server --console-address ":9001" http://minio{1...4}/data{1...2}'
  expose:
    - '9000'
    - '9001'
  environment:
    MINIO_ACCESS_KEY: almog
    MINIO_SECRET_KEY: almog1234
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: minio123
  healthcheck:
    test:
      - CMD
      - curl
      - '-f'
      - 'http://localhost:9000/minio/health/live'
    interval: 30s
    timeout: 20s
    retries: 3
services:
  minio1:
    image: 'quay.io/minio/minio:RELEASE.2021-09-18T18-09-59Z'
    command: 'server --console-address ":9001" http://minio{1...4}/data{1...2}'
    expose:
      - '9000'
      - '9001'
    environment:
      MINIO_ACCESS_KEY: almog
      MINIO_SECRET_KEY: almog1234
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9000/minio/health/live'
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio1
    volumes:
      - 'data1-1:/data1'
      - 'data1-2:/data2'
  minio2:
    image: 'quay.io/minio/minio:RELEASE.2021-09-18T18-09-59Z'
    command: 'server --console-address ":9001" http://minio{1...4}/data{1...2}'
    expose:
      - '9000'
      - '9001'
    environment:
      MINIO_ACCESS_KEY: almog
      MINIO_SECRET_KEY: almog1234
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9000/minio/health/live'
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio2
    volumes:
      - 'data2-1:/data1'
      - 'data2-2:/data2'
  minio3:
    image: 'quay.io/minio/minio:RELEASE.2021-09-18T18-09-59Z'
    command: 'server --console-address ":9001" http://minio{1...4}/data{1...2}'
    expose:
      - '9000'
      - '9001'
    environment:
      MINIO_ACCESS_KEY: almog
      MINIO_SECRET_KEY: almog1234
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9000/minio/health/live'
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio3
    volumes:
      - 'data3-1:/data1'
      - 'data3-2:/data2'
  minio4:
    image: 'quay.io/minio/minio:RELEASE.2021-09-18T18-09-59Z'
    command: 'server --console-address ":9001" http://minio{1...4}/data{1...2}'
    expose:
      - '9000'
      - '9001'
    environment:
      MINIO_ACCESS_KEY: almog
      MINIO_SECRET_KEY: almog1234
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9000/minio/health/live'
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio4
    volumes:
      - 'data4-1:/data1'
      - 'data4-2:/data2'
    ports:
      - '3001:3001'
  video-client:
    container_name: video-client
    image: video-client
    build:
      context: ../video-gallery-client
      dockerfile: Dockerfile
    ports:
      - '80:80'
  nginx:
    image: 'nginx:alpine'
    hostname: minionginx
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '9000:9000'
      - '9001:9001'
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
volumes:
  data1-1: null
  data1-2: null
  data2-1: null
  data2-2: null
  data3-1: null
  data3-2: null
  data4-1: null
  data4-2: null

